query arts($filter: ArtFilterQuery, $pagination: ConnectionArgs, $order: ArtOrderQuery) {
    arts(filter: $filter, pagination: $pagination, order: $order) {
        page {
            edges {
                cursor
                node {
                    id
                    name
                    internal
                    files {
                        artId
                        originalPath
                        watermarkPath
                        uploadedAt
                    }
                    projectId
                    createdAt
                    updatedAt
                    bottomForm
                    artClass
                    form
                    nominalVolume
                    height
                    productType
                    productionMethod
                    ringType
                    project {
                        id
                        name
                    }
                }
            }
            pageInfo {
                startCursor
                endCursor
                hasPreviousPage
                hasNextPage
            }
        }
        pageData {
            count
            take
            skip
        }
    }
}
