query customers($filter: CustomerFilterQuery, $pagination: ConnectionArgs) {
    customers(filter: $filter, pagination: $pagination) {
        id
        name
        active
        createdAt
        updatedAt
    }
}
