query project($id: String!) {
  project(id: $id) {
    id
    name
    internal
    hasDesignDoc
    sfm
    dropNumber
    intercenter
    arts {
      id
      name
      internal
      files {
        artId
        originalPath
        watermarkPath
        uploadedAt
      }
      createdAt
      updatedAt
      bottomForm
      artClass
      form
      nominalVolume
      height
      productType
      productionMethod
      ringType
    }
    factory {
      id
      name
    }
    customer {
      id
      name
    }
    createdAt
    updatedAt
  }
}
